project_id = "boggle-party"

[api]
enabled = true
port = 54321
schemas = ["public", "storage", "graphql_public"]
extra_search_path = ["public", "extensions"]
max_rows = 1000

[db]
port = 54322
shadow_port = 54320
major_version = 17

[studio]
port = 54323

[auth]
enabled = true
site_url = "http://localhost:5173"
additional_redirect_urls = [
  "http://localhost:5173",
  "http://localhost:4173"
]
enable_anonymous_sign_ins = true

[functions.create-or-join-room]
verify_jwt = true

[functions.start-round]
verify_jwt = true

[functions.end-round-and-score]
verify_jwt = true

[functions.set-player-state]
verify_jwt = true
